version: "3.9"
services:
  server1:
    image: pract9_1
    build:
      context: .
      dockerfile: ./server1/Dockerfile
    ports:
      - "8081:8080"
  server2:
    image: pract9_2
    build:
      context: .
      dockerfile: ./server2/Dockerfile
    ports:
      - "8082:8080"
  krakend:
    image: devopsfaith/krakend:latest
    depends_on:
      - server1
      - server2
    ports:
      - "8080:8080"
    volumes:
      - ./kraken:/etc/krakend:rw
