version: "3.9"
services:
  test-postgres:
    image: postgres:latest
    #restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=micropass
      - POSTGRES_USER=microuser
      - POSTGRES_DB=microdb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
